baseURL = 'https://opensource.intive.com'
languageCode = 'en-us'
title = 'intive opensource'
theme = "hugo-coder"

[params]
hideCredits = true
hideCopyright = false
author = "intive"
colorScheme = "auto"
since = 2021
info = "open source is exciting!"
logo = "images/intive_logo_blue.svg"

[[languages.en.menu.main]]
name = "Repositories"
weight = 1
url = "repositories/"

[[languages.en.menu.main]]
name = "Memberships"
weight = 2
url = "memberships/"

[[languages.en.menu.main]]
name = "Blog"
weight = 3
url = "https://intive.com/insights/"

[[languages.en.menu.main]]
name = "Culture"
weight = 4
url = "https://intive.com/careers/cultureblog"

[[languages.en.menu.main]]
name = "Guideline"
weight = 5
url = "guideline"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/intive"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 2
url = "https://www.linkedin.com/company/intive/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 3
url = "https://twitter.com/intive"

[[params.social]]
name = "Medium"
icon = "fa fa-medium"
weight = 4
url = "https://medium.com/intive-developers"
